### PR TITLE
Restore compatibility with openssl 1.1

### PR DESCRIPTION
**Pull request by noonien-d**
Wocky did not compile with recent openssl versions due to api changes. This branch compiles on Arch with openssl 1.1.1.g-1 and on Sailfish SDK with openssl openssl-1.0.2.

I don't really have experience with openssl, so please review well.

### CODE REVIEW

**Comment by rufferson** [comment]
I was actually planning to follow the GIO-TLS patch with openssl removal patch.
It definitely works on arch, but my SFOS sdk in a bad shape to test. Can you try my [nodoc](https://github.com/rufferson/wocky/tree/nodoc) branch?

**Comment by noonien-d** [comment]
I'm fine with that, the less code to maintain the better.

**Comment by Kaffeine** [comment]
@noonien-d would you mind closing this PR now when #5 merged? If I got this right :).

**Comment by noonien-d** [comment]
Obsolete due to #5. Closed.

**Pull request closed without merging**
